export default  [
  {
    _key: "8342088051",
    anonymousFunMode: false,
    backgroundImage: "",
    bonusContribution: 0.01,
    category: "BLACKJACK",
    description: "",
    fpp: 0.01,
    funMode: false,
    height: 0,
    heightRatio: -1,
    helpUrl: "",
    isLive: true,
    isOpen: true,
    jackpotContribution: 0,
    key: "8342088051",
    launchUrls: {
      Android: "8342014092",
      PC: "8342088051",
      iPad: "8342014092",
      iPhone: "8342014092"
    },
    license: "none",
    limit: {
      EUR: { max: "1000", min: "1" },
      GBP: { max: "1000", min: "1" },
      NOK: { max: "10000", min: "10" },
      SEK: { max: "10000", min: "10" },
      USD: { max: "1000", min: "1" }
    },
    logo: "",
    mergedWith: ["8342014092"],
    name: "Blackjack VIP B",
    newGame: false,
    newTable: false,
    openingTime: "24/7",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    popularity: 2223,
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    shortName: "Blackjack VIP B",
    tableID: "8342088051",
    tags: {
      "Evolution Gaming": {
        _key: "Evolution Gaming",
        de: "Evolution Gaming",
        default: "Evolution Gaming",
        fi: "Evolution Gaming",
        no: "Evolution Gaming",
        sv: "Evolution Gaming",
        uk: "Evolution Gaming"
      },
      Live: {
        _key: "Live",
        de: "Live",
        default: "Live",
        fi: "Live",
        no: "Live",
        sv: "Live",
        uk: "Live"
      }
    },
    theoreticalPayOut: 0,
    thumbnail:
      "//static.gammatrix.com/base/_casino/5/55DEF454ED4EE45B6815294067DF8A9E.jpg",
    url:
      "http://casinogmstage.everymatrix.com/Loader/Start/1173/blackjack-evo/?tableID=8342088051",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342001672",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342037464",
      PC: "8342001672",
      iPad: "8342037464",
      iPhone: "8342037464"
    },
    license: "none",
    logo: "",
    name: "Blackjack Platinum VIP",
    openingTime: "UTC 13:00-01:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/5/5A7861C4C8596075656D6BA40BD8AC5F.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342004713",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342004713",
      iPad: "8342004713",
      iPhone: "8342004713"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP C",
    openingTime: "UTC 09:00-04:00",
    platforms: ["iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/C/C8AC941BA20157769F7683F65D6EC7BD.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342001672",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342037464",
      PC: "8342001672",
      iPad: "8342037464",
      iPhone: "8342037464"
    },
    license: "none",
    logo: "",
    name: "Blackjack Platinum VIP",
    openingTime: "UTC 13:00-01:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/5/5A7861C4C8596075656D6BA40BD8AC5F.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342001672",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342037464",
      PC: "8342001672",
      iPad: "8342037464",
      iPhone: "8342037464"
    },
    license: "none",
    logo: "",
    name: "Blackjack Platinum VIP",
    openingTime: "UTC 13:00-01:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/5/5A7861C4C8596075656D6BA40BD8AC5F.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342012801",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342060223",
      PC: "8342012801",
      iPad: "8342060223",
      iPhone: "8342060223"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP F",
    openingTime: "UTC 17:00-01:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/4/40165A2B2A90087AEEA18F70B7123771.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342017133",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342017133", iPad: "8342094064" },
    license: "none",
    logo: "",
    name: "Blackjack A",
    openingTime: "24/7",
    platforms: ["PC", "iPad"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/7/7DC0FE1E7CF10A8BBA058A6CBD8BA136.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342038802",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342038802", iPad: "8342058057" },
    license: "none",
    logo: "",
    name: "Blackjack D",
    openingTime: "UTC 08:00-02:00",
    platforms: ["PC", "iPad"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/4/48E92E0FF4CC3573275BE27F899CD6AA.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342041760",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342053900",
      PC: "8342041760",
      iPad: "8342053900",
      iPhone: "8342053900"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP E",
    openingTime: "UTC 09:00-04:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/5/5D4DB599BD40437CB7C333A852E6FD8E.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342044795",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342012002",
      PC: "8342044795",
      iPad: "8342012002",
      iPhone: "8342012002"
    },
    license: "none",
    logo: "",
    name: "Blackjack E",
    openingTime: "UTC 09:00-04:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/7/7E66EDB74BACE575FFBCF236393169B8.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342057929",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342057929" },
    license: "none",
    logo: "",
    name: "Blackjack VIP C",
    openingTime: "UTC 09:00-04:00",
    platforms: ["PC"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/C/C8AC941BA20157769F7683F65D6EC7BD.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342065746",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342065746", iPad: "8342079726" },
    license: "none",
    logo: "",
    name: "Blackjack B",
    openingTime: "24/7",
    platforms: ["PC", "iPad"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/C/C32C8A400F2D445E854B5A157B9EE781.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342069399",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342003534",
      PC: "8342069399",
      iPad: "8342003534",
      iPhone: "8342003534"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP H",
    openingTime: "UTC 12:00-00:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/7/7460FACE332E52AB29BDDE05AAF44B9F.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342069622",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342069622", iPad: "8342099442" },
    license: "none",
    logo: "",
    name: "Blackjack C",
    openingTime: "24/7",
    platforms: ["PC", "iPad"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/F/F6240015534BBE3FEFB35B90B62F0FB8.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342070267",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342069614",
      PC: "8342070267",
      iPad: "8342069614",
      iPhone: "8342069614"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP G",
    openingTime: "UTC 17:00-01:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/2/29BF975E48815AD621F1843A2A38D5A9.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342076858",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342041255",
      PC: "8342076858",
      iPad: "8342041255",
      iPhone: "8342041255"
    },
    license: "none",
    logo: "",
    name: "Blackjack I",
    openingTime: "UTC 12:00-00:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/7/77B3A2F6AD2202258FE885B535DC94BE.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342090226",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342040729",
      PC: "8342090226",
      iPad: "8342040729",
      iPhone: "8342040729"
    },
    license: "none",
    logo: "",
    name: "Blackjack H",
    openingTime: "UTC 18:00-00:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/1/16CAA0E7634914AD9B0A522E87A2027E.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342091596",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342038834",
      PC: "8342091596",
      iPad: "8342038834",
      iPhone: "8342038834"
    },
    license: "none",
    logo: "",
    name: "Blackjack G",
    openingTime: "UTC 18:00-00:00",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/2/209D47DE89CB7D146E53A8D03914EA7B.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342092417",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342092417" },
    license: "none",
    logo: "",
    name: "Blackjack F",
    openingTime: "UTC 18:00-00:00",
    platforms: ["PC"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/2/209D47DE89CB7D146E53A8D03914EA7B.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342093186",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: {
      Android: "8342013798",
      PC: "8342093186",
      iPad: "8342013798",
      iPhone: "8342013798"
    },
    license: "none",
    logo: "",
    name: "Blackjack VIP A",
    openingTime: "24/7",
    platforms: ["PC", "iPad", "iPhone", "Android"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI",
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/C/C8C14A13700353431FC61428F3A0D011.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  },
  {
    _key: "8342095928",
    backgroundImage: "",
    description: "",
    funMode: false,
    height: 0,
    heightRatio: -1,
    isLive: true,
    launchUrls: { PC: "8342095928" },
    license: "none",
    logo: "",
    name: "Blackjack Party",
    openingTime: "24/7",
    platforms: ["PC"],
    realMode: true,
    restrictedTerritories: [
      "AS",
      "GU",
      "NL",
      "AN",
      "MP",
      "PR",
      "US",
      "UM",
      "VI"
    ],
    thumbnail:
      "//static.gammatrix.com/base/_casino/F/FB7AB25462840D532C2BC4BABF5B49BC.jpg",
    vendor: "EvolutionGaming",
    vipTable: false,
    width: 0
  }
];
